feature/AST-97
TL-Backend/aerpace-ecosystem-device-service pull request #7
Opened 2023-08-30 14:50 UTC by satyanarayanaRaju21

+ list device type api

2023-09-06 15:37 UTC, naveen-repos requested changes

2023-09-06 15:37 UTC, naveen-repos commented on app.js
I am expecting here we need to add cors config. Please check this by calling from another service and add If needed.

2023-09-06 15:37 UTC, naveen-repos commented on src/controllers/device/devices.constant.js
> +  },
get rid of the `default` here

2023-09-06 15:37 UTC, naveen-repos commented on src/controllers/device/devices.constant.js
> +  default: {
Keep this in to formate

2023-09-06 15:37 UTC, naveen-repos commented on src/utils/statusCode.js
> +  STATUS_CODE_NOT_ACCEPTABLE: 406,
Please place needed codes only

2023-09-06 15:37 UTC, naveen-repos commented on src/controllers/device/devices.query.js
> +  FROM ${dbTables.DEVICE_VERSION_TABLE} AS adv
Only get the count of the version's whose status is active.

2023-09-06 15:37 UTC, naveen-repos commented on src/controllers/device/devices.controller.js
> +    const { success, errorCode, message, data } = await getDeviceTypes();
const { success, errorCode, message, data = {} } = await getDeviceTypes();

please remove the return and 30. 

for this API the successful empty response should be 

```
{
   data: {
       device_types: [ ]
    }
}
```

2023-09-06 15:37 UTC, naveen-repos commented on src/controllers/device/devices.controller.js
> +    });
Replace section with this
 
 return successResponse({
        res,
        data: {
          device_types: data,
        },
        message: successResponses.COUNT_FETCH_SUCCESSFULL.message,
        code: statusCodes.STATUS_CODE_SUCCESS,
      });

2023-09-07 10:46 UTC, satyanarayanaRaju21 commented on src/utils/statusCode.js
> +  STATUS_CODE_NOT_ACCEPTABLE: 406,
anna these are common setupCode status codes

2023-09-08 06:46 UTC, merged